version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: compasscar_mysql
    environment:
      MYSQL_ROOT_PASSWORD: maia22
      MYSQL_USER: root
      MYSQL_PASSWORD: maia22
      MYSQL_DATABASE: compasscardb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: compasscar_app
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: maia22
      MYSQL_DATABASE: compasscardb
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
